name: Build and Push

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to GH Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor}}
                #GHCR_PAT with fine grain updated permissions
                password: ${{ secrets.GHCR_PAT}}
            
            - name: Build image
              run: |
                USERNAME="${GITHUB_REPOSITORY_OWNER,,}"
                IMAGE_NAME="ghcr.io/$USERNAME/web-app-concept:latest"

                echo "Building Docker image: $IMAGE_NAME"
                docker build -t $IMAGE_NAME .

            - name: Push image
              run: |
                USERNAME="${GITHUB_REPOSITORY_OWNER,,}"
                IMAGE_NAME="ghcr.io/$USERNAME/web-app-concept:latest"

                echo "Pushing Docker image: $IMAGE_NAME"
                docker push $IMAGE_NAME
              env:
                GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}